from fastapi import FastAPI
from fastapi.responses import Response

app = FastAPI()


@app.get("/download/report.txt")
def download_file():
    content = "FastAPI Report\n==============\nThis is a sample report.\nGenerated by FastAPI.\n"
    return Response(
        content=content,
        media_type="text/plain",
        headers={"Content-Disposition": "attachment; filename=report.txt"},
    )
